# This is a basic workflow to help you get started with Actions

name: Documentation Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Documentation Testcase"
  documentation_testcase:
    # The type of runner that the job will run on
    name: Rapyuta Documentation Job
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
    # Checks to see if any files in the PR match one of the listed file types.
    # This will return true if there's a markdown/RST file that was changed
    # in the PR.
      - name: Dorny Path Filter
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            md:
              - '**/*.md'
            rst:
              - '**/*.rst'
        
      # Use the filter to check if files with a specific file type were changed
      # in the PR. If they were, run the relevant linters. Otherwise, skip.

      - name: Lint Markdown
        if: ${{ steps.filter.outputs.md == 'true' }}
        run: npm run lint:md
      
      - name: Lint Restructured
        if: ${{ steps.filter.outputs.rst == 'true' }}
        run: npm run lint:rst